version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty